### ISSUE TITLE
Possible bug in MoneyFlowIndex?

### ISSUE THREAD

**Issue by ewmailing** [azoyan/talua#1]
Hello, I was just passing through so I don't know if this is a real bug or not. But I was looking over MoneyFlowIndex.lua just trying to educate myself on how the general MFI algorithm works. 

But the following line raises my suspicion:

https://github.com/azoyan/talua/blob/490c53aacfe796d1490fc872563be1f722026a60/src/MoneyFlowIndex.lua#L46

My thinking is you didn't want to to turn this array into a associative array, but instead wanted to append the new value to the end of array like:
```
    self.typical_price[#self.typical_price+1] = typical_price
```

As I said, I was just passing through and don't know if this is a real bug. But as a courtesy, I thought I would report it just in case.

**Comment by azoyan** [comment]
Yes this is issue

**Comment by azoyan** [comment]
Fixed
